name: "Gitcord Release Changelogger"
description: "Pipe changelog information from a GitHub release to Discord."
author: "Tyler J. Russell (Kludge Cyber Systems)"
inputs:
  discord-websocket:
    description: "URL for the Discord websocket. Should be passed via secrets."
    required: true
  release-body:
    description: "Markdown body of the GitHub release, without the header line."
    required: true
  release-name:
    description: "Name to use when sending the release to Discord."
    required: true
outputs:
  discord-api-result:
    description: "Result status from Discord API."
    value: ${{ steps.discord-post.outputs.response }}
runs:
  using: "composite"
  steps:
    - id: "discord-post"
      run: ./gitcord-release-changelogger.sh
      shell: "bash"
      env:
        WEBSOCKET: ${{ inputs.discord-websocket }}
        RELEASE_BODY: ${{ inputs.release-body }}
        RELEASE_NAME: ${{ inputs.release-name }}
